Support for Attribute casts
romanzipp/Laravel-Model-Doc pull request #22
Opened 2023-06-01 08:12 UTC by saulens22

This PR adds support for Eloquent accessor type introduced in Laravel 9.x.

Style / naming might need some updating, but it works functionally :)

2023-06-02 19:23 UTC, romanzipp commented
Nice addition, thanks! Is the PR ready to merge?

2023-06-05 08:46 UTC, saulens22 commented
I believe it's ready to merge. Although I'd recommend you to check if a new config value is needed to turn this off.

2023-06-05 09:04 UTC, saulens22 commented
Although there is (kind of?) a bug / wrong behavior.

If you try to generate documentation for a model that extends another model that already has a cast, it overrides defined docblocks. 

Here's an example with extending [Spatie Media Library](https://github.com/spatie/laravel-medialibrary):

My model `app\Models\Media.php`
```php
use Spatie\MediaLibrary\MediaCollections\Models\Media as MediaModel;

/**
 * [...]
 * @property mixed $type
 * @property mixed $extension
 * @property mixed $human_readable_size
 * @property mixed $preview_url
 * @property mixed $original_url
 */
class Media extends MediaModel
{
}
```

Spatie's model [(source)](https://github.com/spatie/laravel-medialibrary/blob/main/src/MediaCollections/Models/Media.php)
```php
/**
 * @property-read string $type
 * @property-read string $extension
 * @property-read string $humanReadableSize
 * @property-read string $previewUrl
 * @property-read string $originalUrl
 */
class Media extends Model
{
    // [...]
    protected function type(): Attribute
    {
        return Attribute::get(
            function () {
                $type = $this->getTypeFromExtension();

                if ($type !== self::TYPE_OTHER) {
                    return $type;
                }

                return $this->getTypeFromMime();
            }
        );
    }
}
```

`model-doc` overwrites existing parent model's docs.

I'm not sure what behavior is expected here and if this use case is / should be supported.

2023-06-28 12:50 UTC, romanzipp commented
I'm not using casts by myself (i think its a bad coding pattern) but wont the be exposed in snake case instead of camel case? `originalUrl()` cast -> `original_url` "attribute"

2023-06-29 13:34 UTC, saulens22 commented
Both are accessible when using newer `Attribute:make`.

Using `getSomethingAttribute` only checks for `Str::sturdly('Something')`.

Laravel's code: https://github.com/illuminate/database/blob/master/Eloquent/Concerns/HasAttributes.php#L1046-L1081

![image](https://github.com/romanzipp/Laravel-Model-Doc/assets/9000854/001624f9-12d5-4e13-8554-57abc71ae02b)

2023-07-17 11:51 UTC, romanzipp requested changes
This should cover all cases for casts using Attributes. Tests need to be adjusted

2023-07-17 11:51 UTC, romanzipp commented on src/Services/DocumentationGenerator.php
> +            $tag->setVariable(Str::snake($method->getName()));
```suggestion
            $camelCaseTag = new PropertyTag();
            $camelCaseTag->setVariable($methodName = $method->getName());
```

2023-07-17 11:51 UTC, romanzipp commented on src/Services/DocumentationGenerator.php
> +            yield $tag;
```suggestion
            $camelCaseTag->setType($returnType);

            $snakeCaseTag = clone $camelCaseTag;
            $snakeCaseTag->setVariable(Str::snake($methodName));

            yield $camelCaseTag;
            yield $snakeCaseTag;
```

2023-08-02 07:07 UTC, romanzipp commented
Yep, looks good to me. Thanks for contribution! I was really impressed how you managed to incorporate the changes to match my previous program flow & syntax!

2023-08-02 07:07 UTC, merged